flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- Chart-1.5
- Chart-cairo-1.5
- MonadRandom-0.4
- OneTuple-0.2.1
- StateVar-1.1.0.0
- adjunctions-4.2.1
- base-orphans-0.4.0
- bifunctors-5
- bson-0.3.1
- byteable-0.1.1
- cairo-0.13.1.0
- colour-2.3.3
- comonad-4.2.6
- contravariant-1.3.1.1
- cryptohash-0.11.6
- data-binary-ieee754-0.4.4
- data-default-class-0.0.1
- distributive-0.4.4
- exceptions-0.8.0.2
- extra-1.3
- free-4.12.1
- hashable-1.2.3.3
- hashtables-1.2.0.2
- hs-gchart-0.4.1
- kan-extensions-4.2.2
- lens-4.11
- lifted-base-0.2.3.6
- monad-control-1.0.0.4
- mongoDB-2.0.5
- mtl-2.1.3.1
- nats-1
- network-2.6.2.1
- operational-0.2.3.2
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- random-shuffle-0.0.4
- reflection-1.5.2.1
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- stm-2.4.4
- tagged-0.8.1
- text-1.2.1.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.3
- tuple-0.3.0.2
- unordered-containers-0.2.5.1
- utf8-string-1
- vector-0.10.12.3
- void-0.7
resolver: ghc-7.8
