flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- OneTuple-0.2.1
- bson-0.3.1
- byteable-0.1.1
- cryptohash-0.11.6
- data-accessor-0.2.2.6
- data-accessor-transformers-0.2.1.6
- data-binary-ieee754-0.4.4
- directory-1.2.2.1
- exceptions-0.8.0.2
- extra-1.3
- gnuplot-0.5.4
- hashable-1.2.3.3
- hashtables-1.2.0.2
- hs-gchart-0.4.1
- lifted-base-0.2.3.6
- monad-control-1.0.0.4
- mongoDB-2.0.5
- mtl-2.1.3.1
- network-2.6.2.1
- parsec-3.1.9
- primitive-0.6
- process-1.2.3.0
- random-1.1
- random-shuffle-0.0.4
- stm-2.4.4
- temporary-1.2.0.3
- text-1.2.1.1
- time-1.5.0.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.3
- tuple-0.3.0.2
- unix-2.7.1.0
- utility-ht-0.0.10
- vector-0.10.12.3
resolver: ghc-7.8
